// AUTO-GENERATED — scraped from taylormadegolf.co.za / .com

export interface Product {
  id: string;
  name: string;
  category: 'Drivers' | 'Fairways' | 'Hybrids' | 'Irons' | 'Putters' | 'Wedges' | 'Golf Balls' | 'Bags' | 'Accessories' | 'Club Sets';
  price: number;
  originalPrice?: number;
  image: string;
  badge?: string;
  description?: string;
  specs?: string[];
  isNew?: boolean;
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(price);
}

export const products: Product[] = [
  // ── DRIVERS ───────────────────────────────────────────────────
  {
    id: 'qi4d-max-lite-driver',
    name: 'Qi4D Max Lite Driver',
    category: 'Drivers',
    price: 399,
    originalPrice: 500,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Max_Lite_Driver.jpg',
    description: 'Qi4D Max Lite Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-ls-driver',
    name: 'Qi4D LS Driver',
    category: 'Drivers',
    price: 599,
    originalPrice: 720,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_LS_Driver.jpg',
    description: 'Qi4D LS Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-driver',
    name: 'Qi4D Driver',
    category: 'Drivers',
    price: 499,
    originalPrice: 630,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Driver.jpg',
    description: 'Qi4D Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-driver',
    name: 'Qi4D Max Driver',
    category: 'Drivers',
    price: 499,
    originalPrice: 630,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Max_Driver.jpg',
    description: 'Qi4D Max Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'sim2-max-driver',
    name: 'SIM2 Max Driver',
    category: 'Drivers',
    price: 299,
    originalPrice: 380,
    badge: 'Sale',
    image: '/drivers/SIM2_Max_Driver.jpg',
    description: 'SIM2 Max Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── FAIRWAYS ──────────────────────────────────────────────────
  {
    id: 'qi4d-fairway',
    name: 'Qi4D Fairway',
    category: 'Fairways',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Fairway.jpg',
    description: 'Qi4D Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-fairway',
    name: 'Qi4D Max Fairway',
    category: 'Fairways',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Max_Fairway.jpg',
    description: 'Qi4D Max Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-tour-fairway',
    name: 'Qi4D Tour Fairway',
    category: 'Fairways',
    price: 399,
    originalPrice: 500,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Tour_Fairway.jpg',
    description: 'Qi4D Tour Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'sim2-max-fairway',
    name: 'SIM2 Max Fairway',
    category: 'Fairways',
    price: 249,
    originalPrice: 320,
    badge: 'Sale',
    image: '/fairways/SIM2_Max_Fairway.jpg',
    description: 'SIM2 Max Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── HYBRIDS ───────────────────────────────────────────────────
  {
    id: 'sim2-max-rescue',
    name: 'SIM2 Max Rescue',
    category: 'Hybrids',
    price: 249,
    originalPrice: 320,
    badge: 'Sale',
    image: '/hybrids/SIM2_Max_Rescue.jpg',
    description: 'SIM2 Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi35-max-rescue',
    name: 'Qi35 Max Rescue',
    category: 'Hybrids',
    price: 279,
    originalPrice: 350,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi35_Max_Rescue.jpg',
    description: 'Qi35 Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi35-max-lite-rescue',
    name: 'Qi35 Max Lite Rescue',
    category: 'Hybrids',
    price: 249,
    originalPrice: 320,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi35_Max_Lite_Rescue.jpg',
    description: 'Qi35 Max Lite Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-rescue',
    name: 'Qi4D Rescue',
    category: 'Hybrids',
    price: 299,
    originalPrice: 380,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Rescue.jpg',
    description: 'Qi4D Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-rescue',
    name: 'Qi4D Max Rescue',
    category: 'Hybrids',
    price: 299,
    originalPrice: 380,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Max_Rescue.jpg',
    description: 'Qi4D Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-lite-rescue',
    name: 'Qi4D Max Lite Rescue',
    category: 'Hybrids',
    price: 249,
    originalPrice: 320,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Max_Lite_Rescue.jpg',
    description: 'Qi4D Max Lite Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── IRONS ─────────────────────────────────────────────────────
  {
    id: 'p770-irons',
    name: 'P·770 Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Best Seller',
    image: '/irons/P·770_Irons.jpg',
    description: 'P·770 Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p790-irons',
    name: 'P·790 Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Best Seller',
    image: '/irons/P·790_Irons.jpg',
    description: 'P·790 Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7cb-irons',
    name: 'P·7CB Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/P·7CB_Irons.jpg',
    description: 'P·7CB Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7mb-irons-(3-pw)',
    name: 'P·7MB Irons (3-PW)',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/P·7MB_Irons_(3-PW).jpg',
    description: 'P·7MB Irons (3-PW) — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7tw-irons',
    name: 'P·7TW Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Best Seller',
    image: '/irons/P·7TW_Irons.png',
    description: 'P·7TW Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'pdhy-utility-iron',
    name: 'P∙DHY Utility Iron',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/P∙DHY_Utility_Iron.jpg',
    description: 'P∙DHY Utility Iron — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'pudi-utility-iron',
    name: 'P∙UDI Utility Iron',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/P∙UDI_Utility_Iron.jpg',
    description: 'P∙UDI Utility Iron — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-hl-irons',
    name: 'Qi HL Irons',
    category: 'Irons',
    price: 899,
    originalPrice: 1080,
    badge: 'Sale',
    image: '/irons/Qi_HL_Irons.jpg',
    description: 'Qi HL Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-irons',
    name: 'Qi Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/Qi_Irons.jpg',
    description: 'Qi Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-max-hl-irons',
    name: 'Qi Max HL Irons',
    category: 'Irons',
    price: 999,
    originalPrice: 1200,
    badge: 'Sale',
    image: '/irons/Qi_Max_HL_Irons.jpg',
    description: 'Qi Max HL Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-max-irons',
    name: 'Qi Max Irons',
    category: 'Irons',
    price: 1099,
    originalPrice: 1320,
    badge: 'Sale',
    image: '/irons/Qi_Max_Irons.jpg',
    description: 'Qi Max Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-womens-irons',
    name: 'Qi Womens Irons',
    category: 'Irons',
    price: 799,
    originalPrice: 960,
    badge: 'Sale',
    image: '/irons/Qi_Womens_Irons.jpg',
    description: 'Qi Womens Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── PUTTERS ───────────────────────────────────────────────────
  {
    id: 'spider-zt-black',
    name: 'Spider ZT Black',
    category: 'Putters',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Black.jpg',
    description: 'Spider ZT Black — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt-long',
    name: 'Spider ZT Long',
    category: 'Putters',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Long.jpg',
    description: 'Spider ZT Long — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt-counterbalance',
    name: 'Spider ZT Counterbalance',
    category: 'Putters',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Counterbalance.jpg',
    description: 'Spider ZT Counterbalance — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt',
    name: 'Spider ZT',
    category: 'Putters',
    price: 349,
    originalPrice: 440,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT.jpg',
    description: 'Spider ZT — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'tp-black-collection',
    name: 'TP Black Collection',
    category: 'Putters',
    price: 449,
    originalPrice: 570,
    badge: 'Sale',
    image: '/putters/TP_Black_Collection.jpg',
    description: 'TP Black Collection — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-s',
    name: 'Spider Tour S',
    category: 'Putters',
    price: 299,
    originalPrice: 380,
    badge: 'Sale',
    image: '/putters/Spider_Tour_S.jpg',
    description: 'Spider Tour S — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-z',
    name: 'Spider Tour Z',
    category: 'Putters',
    price: 299,
    originalPrice: 380,
    badge: 'Sale',
    image: '/putters/Spider_Tour_Z.jpg',
    description: 'Spider Tour Z — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-x',
    name: 'Spider Tour X',
    category: 'Putters',
    price: 349,
    originalPrice: 440,
    badge: 'Best Seller',
    image: '/putters/Spider_Tour_X.jpg',
    description: 'Spider Tour X — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-v',
    name: 'Spider Tour V',
    category: 'Putters',
    price: 299,
    originalPrice: 380,
    badge: 'Sale',
    image: '/putters/Spider_Tour_V.jpg',
    description: 'Spider Tour V — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour',
    name: 'Spider Tour',
    category: 'Putters',
    price: 299,
    originalPrice: 380,
    badge: 'Sale',
    image: '/putters/Spider_Tour.jpg',
    description: 'Spider Tour — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── WEDGES ────────────────────────────────────────────────────
  {
    id: 'hi-toe-4-wedge',
    name: 'Hi-Toe 4 Wedge',
    category: 'Wedges',
    price: 179,
    originalPrice: 230,
    badge: 'New',
    isNew: true,
    image: '/wedges/Hi-Toe_4_Wedge.jpg',
    description: 'Hi-Toe 4 Wedge — premium TaylorMade wedges built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'mg5-satin-chrome-wedge',
    name: 'MG5 Satin Chrome Wedge',
    category: 'Wedges',
    price: 179,
    originalPrice: 230,
    badge: 'New',
    isNew: true,
    image: '/wedges/MG5_Satin_Chrome_Wedge.jpg',
    description: 'MG5 Satin Chrome Wedge — premium TaylorMade wedges built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'mg5-charcoal-wedge',
    name: 'MG5 Charcoal Wedge',
    category: 'Wedges',
    price: 179,
    originalPrice: 230,
    badge: 'New',
    isNew: true,
    image: '/wedges/MG5_Charcoal_Wedge.jpg',
    description: 'MG5 Charcoal Wedge — premium TaylorMade wedges built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'mg5-tiger-woods-grind-wedge',
    name: 'MG5 Tiger Woods Grind Wedge',
    category: 'Wedges',
    price: 199,
    originalPrice: 250,
    badge: 'New',
    isNew: true,
    image: '/wedges/MG5_Tiger_Woods_Grind_Wedge.jpg',
    description: 'MG5 Tiger Woods Grind Wedge — premium TaylorMade wedges built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'milled-grind-chrome',
    name: 'Milled Grind Chrome',
    category: 'Wedges',
    price: 169,
    originalPrice: 220,
    badge: 'Sale',
    image: '/wedges/Milled_Grind_Chrome.jpg',
    description: 'Milled Grind Chrome — premium TaylorMade wedges built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
];

export const categories = [
  { id: 'all',         label: 'All Products' },
  { id: 'Club Sets',   label: 'Club Sets'    },
  { id: 'Drivers',     label: 'Drivers'      },
  { id: 'Fairways',    label: 'Fairways'     },
  { id: 'Hybrids',     label: 'Hybrids'      },
  { id: 'Irons',       label: 'Irons'        },
  { id: 'Putters',     label: 'Putters'      },
  { id: 'Wedges',      label: 'Wedges'       },
  { id: 'Golf Balls',  label: 'Golf Balls'   },
  { id: 'Bags',        label: 'Bags'         },
  { id: 'Accessories', label: 'Accessories'  },
];
