// AUTO-GENERATED — scraped from taylormadegolf.co.za / .com

export interface Product {
  id: string;
  name: string;
  category: 'Drivers' | 'Fairways' | 'Hybrids' | 'Irons' | 'Putters' | 'Club Sets' | 'Golf Carts';
  price: number;
  image: string;
  badge?: string;
  description?: string;
  specs?: string[];
  isNew?: boolean;
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(price);
}

export const products: Product[] = [
  // ── CLUB SETS ─────────────────────────────────────────────────
  {
    id: 'rbz-complete-set',
    name: 'RBZ Complete Set',
    category: 'Club Sets',
    price: 1400,
    image: '/club-sets/RBZ_Complete_Set.jpg',
    description: 'RBZ Complete Set — 11-piece set including Driver, 3 Wood, 4 Rescue, 6-Iron through SW, Putter, and Cart Bag.',
    specs: ['11 Pieces', 'Driver, 3 Wood, 4 Rescue', '6-Iron through SW', 'Putter + Cart Bag'],
  },
  {
    id: 'kalea-gold-package-set-cart',
    name: "Kalea Gold Package Set (Women's)",
    category: 'Club Sets',
    price: 1900,
    image: '/club-sets/Kalea_Gold_Package_Set.jpg',
    description: "Kalea Gold Women's Package Set — 10-piece set including Driver, 5 Wood, 6 Hybrid, 7-Iron through PW, SW, Putter, and Bag.",
    specs: ['10 Pieces', 'Driver, 5 Wood, 6 Hybrid', '7-Iron through SW', 'Putter + Cart Bag'],
  },
  {
    id: 'kalea-gold-stand-bag-set',
    name: "Kalea Gold Stand Bag Set (Women's)",
    category: 'Club Sets',
    price: 1900,
    image: '/club-sets/Kalea_Gold_Stand_Bag_Set.jpg',
    description: "Kalea Gold Women's Stand Bag Set — 10-piece set including Driver, 5 Wood, 6 Hybrid, 7-Iron through PW, SW, Putter, and Stand Bag.",
    specs: ['10 Pieces', 'Driver, 5 Wood, 6 Hybrid', '7-Iron through SW', 'Putter + Stand Bag'],
  },
  {
    id: 'rbz-womens-complete-set',
    name: "RBZ Women's Complete Set",
    category: 'Club Sets',
    price: 1400,
    image: '/club-sets/RBZ_Womens_Complete_Set.jpg',
    description: "RBZ Women's Complete Set — 10-piece set including Driver, 5 Wood, 5 Rescue, 7-Iron through SW, Putter, and Cart Bag.",
    specs: ['10 Pieces', 'Driver, 5 Wood, 5 Rescue', '7-Iron through SW', 'Putter + Cart Bag'],
  },
  {
    id: 'team-taylormade-junior-set-size-1',
    name: 'Team TaylorMade Junior Set (Ages 4–6)',
    category: 'Club Sets',
    price: 300,
    image: '/club-sets/Junior_Set_Size_1.jpg',
    description: 'Team TaylorMade Junior Set Size 1 — 5-piece set for ages 4–6. Includes Fairway, 7-Iron, SW, Putter, and Bag.',
    specs: ['5 Pieces', 'Ages 4–6', 'Fairway, 7-Iron, SW', 'Putter + Bag'],
  },
  {
    id: 'team-taylormade-junior-set-size-2',
    name: 'Team TaylorMade Junior Set (Ages 7–9)',
    category: 'Club Sets',
    price: 450,
    image: '/club-sets/Junior_Set_Size_2.jpg',
    description: 'Team TaylorMade Junior Set Size 2 — 6-piece set for ages 7–9. Includes Fairway, 7-Iron, 9-Iron, SW, Putter, and Bag.',
    specs: ['6 Pieces', 'Ages 7–9', 'Fairway, 7-Iron, 9-Iron, SW', 'Putter + Bag'],
  },
  {
    id: 'team-taylormade-junior-set-size-3',
    name: 'Team TaylorMade Junior Set (Ages 10–12)',
    category: 'Club Sets',
    price: 550,
    image: '/club-sets/Junior_Set_Size_3.jpg',
    description: 'Team TaylorMade Junior Set Size 3 — 8-piece set for ages 10–12. Includes Driver, Fairway, Rescue, 7-Iron, 9-Iron, SW, Putter, and Bag.',
    specs: ['8 Pieces', 'Ages 10–12', 'Driver, Fairway, Rescue', '7-Iron, 9-Iron, SW, Putter + Bag'],
  },

  // ── DRIVERS ───────────────────────────────────────────────────
  {
    id: 'qi4d-max-lite-driver',
    name: 'Qi4D Max Lite Driver',
    category: 'Drivers',
    price: 519,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Max_Lite_Driver.jpg',
    description: 'Qi4D Max Lite Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-ls-driver',
    name: 'Qi4D LS Driver',
    category: 'Drivers',
    price: 779,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_LS_Driver.jpg',
    description: 'Qi4D LS Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-driver',
    name: 'Qi4D Driver',
    category: 'Drivers',
    price: 649,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Driver.jpg',
    description: 'Qi4D Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-driver',
    name: 'Qi4D Max Driver',
    category: 'Drivers',
    price: 649,
    badge: 'New',
    isNew: true,
    image: '/drivers/Qi4D_Max_Driver.jpg',
    description: 'Qi4D Max Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'sim2-max-driver',
    name: 'SIM2 Max Driver',
    category: 'Drivers',
    price: 739,
    badge: 'Best Seller',
    image: '/drivers/SIM2_Max_Driver.jpg',
    description: 'SIM2 Max Driver — premium TaylorMade drivers built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── FAIRWAYS ──────────────────────────────────────────────────
  {
    id: 'qi4d-fairway',
    name: 'Qi4D Fairway',
    category: 'Fairways',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Fairway.jpg',
    description: 'Qi4D Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-fairway',
    name: 'Qi4D Max Fairway',
    category: 'Fairways',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Max_Fairway.jpg',
    description: 'Qi4D Max Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-tour-fairway',
    name: 'Qi4D Tour Fairway',
    category: 'Fairways',
    price: 519,
    badge: 'New',
    isNew: true,
    image: '/fairways/Qi4D_Tour_Fairway.jpg',
    description: 'Qi4D Tour Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'sim2-max-fairway',
    name: 'SIM2 Max Fairway',
    category: 'Fairways',
    price: 324,
    image: '/fairways/SIM2_Max_Fairway.jpg',
    description: 'SIM2 Max Fairway — premium TaylorMade fairways built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── HYBRIDS ───────────────────────────────────────────────────
  {
    id: 'sim2-max-rescue',
    name: 'SIM2 Max Rescue',
    category: 'Hybrids',
    price: 324,
    image: '/hybrids/SIM2_Max_Rescue.jpg',
    description: 'SIM2 Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi35-max-rescue',
    name: 'Qi35 Max Rescue',
    category: 'Hybrids',
    price: 363,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi35_Max_Rescue.jpg',
    description: 'Qi35 Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi35-max-lite-rescue',
    name: 'Qi35 Max Lite Rescue',
    category: 'Hybrids',
    price: 324,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi35_Max_Lite_Rescue.jpg',
    description: 'Qi35 Max Lite Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-rescue',
    name: 'Qi4D Rescue',
    category: 'Hybrids',
    price: 389,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Rescue.jpg',
    description: 'Qi4D Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-rescue',
    name: 'Qi4D Max Rescue',
    category: 'Hybrids',
    price: 389,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Max_Rescue.jpg',
    description: 'Qi4D Max Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi4d-max-lite-rescue',
    name: 'Qi4D Max Lite Rescue',
    category: 'Hybrids',
    price: 324,
    badge: 'New',
    isNew: true,
    image: '/hybrids/Qi4D_Max_Lite_Rescue.jpg',
    description: 'Qi4D Max Lite Rescue — premium TaylorMade hybrids built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── IRONS ─────────────────────────────────────────────────────
  {
    id: 'p770-irons',
    name: 'P·770 Irons',
    category: 'Irons',
    price: 1299,
    badge: 'Best Seller',
    image: '/irons/P·770_Irons.jpg',
    description: 'P·770 Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p790-irons',
    name: 'P·790 Irons',
    category: 'Irons',
    price: 1299,
    badge: 'Best Seller',
    image: '/irons/P·790_Irons.jpg',
    description: 'P·790 Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7cb-irons',
    name: 'P·7CB Irons',
    category: 'Irons',
    price: 1299,
    image: '/irons/P·7CB_Irons.jpg',
    description: 'P·7CB Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7mb-irons-(3-pw)',
    name: 'P·7MB Irons (3-PW)',
    category: 'Irons',
    price: 1299,
    image: '/irons/P·7MB_Irons_(3-PW).jpg',
    description: 'P·7MB Irons (3-PW) — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'p7tw-irons',
    name: 'P·7TW Irons',
    category: 'Irons',
    price: 1299,
    badge: 'Best Seller',
    image: '/irons/P·7TW_Irons.png',
    description: 'P·7TW Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'pdhy-utility-iron',
    name: 'P∙DHY Utility Iron',
    category: 'Irons',
    price: 1299,
    image: '/irons/P∙DHY_Utility_Iron.jpg',
    description: 'P∙DHY Utility Iron — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'pudi-utility-iron',
    name: 'P∙UDI Utility Iron',
    category: 'Irons',
    price: 1299,
    image: '/irons/P∙UDI_Utility_Iron.jpg',
    description: 'P∙UDI Utility Iron — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-hl-irons',
    name: 'Qi HL Irons',
    category: 'Irons',
    price: 1169,
    image: '/irons/Qi_HL_Irons.jpg',
    description: 'Qi HL Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-irons',
    name: 'Qi Irons',
    category: 'Irons',
    price: 1299,
    image: '/irons/Qi_Irons.jpg',
    description: 'Qi Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-max-hl-irons',
    name: 'Qi Max HL Irons',
    category: 'Irons',
    price: 1299,
    image: '/irons/Qi_Max_HL_Irons.jpg',
    description: 'Qi Max HL Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-max-irons',
    name: 'Qi Max Irons',
    category: 'Irons',
    price: 1429,
    image: '/irons/Qi_Max_Irons.jpg',
    description: 'Qi Max Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'qi-womens-irons',
    name: 'Qi Womens Irons',
    category: 'Irons',
    price: 1039,
    image: '/irons/Qi_Womens_Irons.jpg',
    description: 'Qi Womens Irons — premium TaylorMade irons built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  // ── PUTTERS ───────────────────────────────────────────────────
  {
    id: 'spider-zt-black',
    name: 'Spider ZT Black',
    category: 'Putters',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Black.jpg',
    description: 'Spider ZT Black — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt-long',
    name: 'Spider ZT Long',
    category: 'Putters',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Long.jpg',
    description: 'Spider ZT Long — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt-counterbalance',
    name: 'Spider ZT Counterbalance',
    category: 'Putters',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT_Counterbalance.jpg',
    description: 'Spider ZT Counterbalance — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-zt',
    name: 'Spider ZT',
    category: 'Putters',
    price: 454,
    badge: 'New',
    isNew: true,
    image: '/putters/Spider_ZT.jpg',
    description: 'Spider ZT — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'tp-black-collection',
    name: 'TP Black Collection',
    category: 'Putters',
    price: 584,
    badge: 'Best Seller',
    image: '/putters/TP_Black_Collection.jpg',
    description: 'TP Black Collection — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-s',
    name: 'Spider Tour S',
    category: 'Putters',
    price: 389,
    image: '/putters/Spider_Tour_S.jpg',
    description: 'Spider Tour S — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-z',
    name: 'Spider Tour Z',
    category: 'Putters',
    price: 389,
    image: '/putters/Spider_Tour_Z.jpg',
    description: 'Spider Tour Z — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-x',
    name: 'Spider Tour X',
    category: 'Putters',
    price: 454,
    badge: 'Best Seller',
    image: '/putters/Spider_Tour_X.jpg',
    description: 'Spider Tour X — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour-v',
    name: 'Spider Tour V',
    category: 'Putters',
    price: 389,
    image: '/putters/Spider_Tour_V.jpg',
    description: 'Spider Tour V — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },
  {
    id: 'spider-tour',
    name: 'Spider Tour',
    category: 'Putters',
    price: 389,
    image: '/putters/Spider_Tour.jpg',
    description: 'Spider Tour — premium TaylorMade putters built for distance and performance.',
    specs: ['Premium TaylorMade technology', 'Tour-proven performance'],
  },

  // ── GOLF CARTS ─────────────────────────────────────────────────────────────
  {
    id: 'gc-k2c-red',
    name: '4 Seater Utility Golf Cart K2C',
    category: 'Golf Carts',
    price: 8999,
    image: '/golf-carts/k2c-red.jpg',
    badge: 'Best Seller',
    description: 'Premium 4-seater utility golf cart with powerful electric motor, comfortable seating, and durable build for golf courses and resorts.',
    specs: ['4 passenger capacity', 'Electric drive system', 'Heavy-duty chassis', 'Available in Red', 'LED headlights & taillights', 'USB charging ports'],
  },
  {
    id: 'gc-r2c-white',
    name: '4 Seater Utility Golf Cart R2C',
    category: 'Golf Carts',
    price: 8499,
    image: '/golf-carts/r2c-white.jpg',
    description: 'Elegant white 4-seater utility golf cart with smooth ride, ideal for golf courses and hospitality venues.',
    specs: ['4 passenger capacity', 'Electric drive system', 'Rear utility seat', 'Available in White', 'Windshield included', 'USB charging ports'],
  },
  {
    id: 'gc-e2-white',
    name: '2 Seater Golf Cart E2',
    category: 'Golf Carts',
    price: 5499,
    image: '/golf-carts/e2-white.jpg',
    description: 'Classic 2-seater electric golf cart, lightweight and agile — perfect for individual rounds and resort use.',
    specs: ['2 passenger capacity', 'Electric drive system', 'Compact design', 'Available in White', 'Golf bag holder', 'Easy-access charging port'],
  },
  {
    id: 'gc-e2c-grey',
    name: '4 Seater Utility Golf Cart E2C',
    category: 'Golf Carts',
    price: 8299,
    image: '/golf-carts/e2c-grey.jpg',
    description: 'Stylish grey 4-seater utility cart combining comfort and practicality for any golf course or luxury resort.',
    specs: ['4 passenger capacity', 'Electric drive system', 'Padded bench seats', 'Available in Grey', 'Canopy roof', 'Rear storage rack'],
  },
  {
    id: 'gc-e2-grey',
    name: '2 Seater Golf Cart E2 (New Arrival)',
    category: 'Golf Carts',
    price: 5699,
    image: '/golf-carts/e2-grey.jpg',
    badge: 'New',
    description: 'Brand new 2-seater E2 golf cart in sleek grey. Updated design with improved battery range and ergonomics.',
    specs: ['2 passenger capacity', 'Extended battery range', 'Updated ergonomic design', 'Available in Grey', 'Digital dashboard', 'Regenerative braking'],
  },
  {
    id: 'gc-z2c-royal-blue',
    name: '4 Seater Utility Golf Cart Z2C',
    category: 'Golf Carts',
    price: 9299,
    image: '/golf-carts/z2c-royal-blue.jpg',
    description: 'Bold royal blue 4-seater Z2C utility cart with premium finish and enhanced suspension for rough terrain.',
    specs: ['4 passenger capacity', 'Enhanced suspension', 'All-terrain tyres', 'Available in Royal Blue', 'Premium sound system', 'Custom body kit'],
  },
  {
    id: 'gc-z2c-cerulean',
    name: '4 Seater Utility Golf Cart Z2C Cerulean',
    category: 'Golf Carts',
    price: 9299,
    image: '/golf-carts/z2c-cerulean.jpg',
    description: 'Striking cerulean blue Z2C utility cart with all-terrain capability and luxury comfort features.',
    specs: ['4 passenger capacity', 'All-terrain capability', 'Luxury seating', 'Available in Cerulean', 'LED accent lighting', 'Rear grab handles'],
  },
  {
    id: 'gc-e2c-royal-blue',
    name: '4 Seater Golf Cart E2C Royal Blue',
    category: 'Golf Carts',
    price: 8499,
    image: '/golf-carts/e2c-royal-blue.jpg',
    description: 'Eye-catching royal blue E2C 4-seater golf cart with smooth electric drive and premium finish.',
    specs: ['4 passenger capacity', 'Smooth electric drive', 'Premium finish', 'Available in Royal Blue', 'Padded headrests', 'Safety seatbelts'],
  },
  {
    id: 'gc-r2-royal-blue',
    name: '2 Seater Utility Golf Cart R2',
    category: 'Golf Carts',
    price: 6299,
    image: '/golf-carts/r2-royal-blue.jpg',
    description: 'Compact 2-seater utility cart with rear storage bed — ideal for maintenance crews and course rangers.',
    specs: ['2 passenger capacity', 'Rear utility cargo bed', 'Heavy-duty frame', 'Available in Royal Blue', 'High ground clearance', 'Tow hitch included'],
  },
  {
    id: 'gc-e2b-white',
    name: '2 Seater Golf Cart with Cargo Box E2B',
    category: 'Golf Carts',
    price: 6799,
    image: '/golf-carts/e2b-white.jpg',
    badge: 'New',
    description: 'Versatile 2-seater E2B golf cart with integrated cargo box — carry clubs, refreshments, and gear with ease.',
    specs: ['2 passenger capacity', 'Integrated cargo box', 'Lockable storage', 'Available in White', 'Easy-access design', 'Weatherproof cargo lid'],
  },
  {
    id: 'gc-z2cj-blue',
    name: '4 Seater Utility Golf Cart Z2CJ',
    category: 'Golf Carts',
    price: 9599,
    image: '/golf-carts/z2cj-blue.jpg',
    description: 'Top-of-the-line Z2CJ 4-seater with enhanced features, premium interior, and powerful motor for any terrain.',
    specs: ['4 passenger capacity', 'High-torque motor', 'Premium interior trim', 'Available in Blue', 'Advanced braking system', 'Weather canopy'],
  },
  {
    id: 'gc-z2c-camouflage',
    name: '4 Seater Utility Golf Cart Z2C Camouflage',
    category: 'Golf Carts',
    price: 9799,
    image: '/golf-carts/z2c-camouflage.jpg',
    badge: 'Best Seller',
    description: 'Distinctive camouflage Z2C 4-seater utility cart — rugged, powerful, and built for off-course adventures.',
    specs: ['4 passenger capacity', 'Off-road capability', 'Camouflage wrap', 'Rugged suspension', 'Winch-ready front', 'All-terrain tyres'],
  },
];

export const categories = [
  { id: 'all',        label: 'All Products' },
  { id: 'Club Sets',  label: 'Club Sets'    },
  { id: 'Drivers',    label: 'Drivers'      },
  { id: 'Fairways',   label: 'Fairways'     },
  { id: 'Hybrids',    label: 'Hybrids'      },
  { id: 'Irons',      label: 'Irons'        },
  { id: 'Putters',    label: 'Putters'      },
  { id: 'Golf Carts', label: 'Golf Carts'   },
];
